
const carts = [
    {
        "idx": 1,
        "id": 10,
        "title": "Men1",
        "gender": "men",
        "img": "./images/m1.jpeg",
        "price": 190,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms1.jpeg",
        "discount": 50
    },
    {
        "idx": 2,
        "id": 20,
        "title": "Men2",
        "gender": "men",
        "img": "./images/m2.jpeg",
        "price": 10,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms2.jpeg",
        "discount": 10
    },
    {
        "idx": 3,
        "id": 30,
        "title": "Men3",
        "gender": "men",
        "img": "./images/m3.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms3.jpeg",
        "discount": 20
    },
    {
        "idx": 4,
        "id": 40,
        "title": "Men4",
        "gender": "men",
        "img": "./images/m4.jpeg",
        "price": 490,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms4.jpeg",
        "discount": 90
    },
    {
        "idx": 5,
        "id": 50,
        "title": "Men1",
        "gender": "men",
        "img": "./images/m5.jpeg",
        "price": 490,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms5.jpeg",
        "discount": 60
    },
    {
        "idx": 6,
        "id": 60,
        "title": "Women1",
        "gender": "women",
        "img": "./images/w1.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ws1.jpeg",
        "discount": 35
    },
    {
        "idx": 7,
        "id": 70,
        "title": "Women2",
        "gender": "women",
        "img": "./images/w2.jpeg",
        "price": 100,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ws2.jpeg",
        "discount": 25
    },
    {
        "idx": 8,
        "id": 80,
        "title": "Women3",
        "gender": "women",
        "img": "./images/w3.jpeg",
        "price": 100,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ws3.jpeg",
        "discount": 15
    },
    {
        "idx": 9,
        "id": 90,
        "title": "Women4",
        "gender": "women",
        "img": "./images/w4.jpeg",
        "price": 170,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ws4.jpeg",
        "discount": 95
    },
    {
        "idx": 10,
        "id": 100,
        "title": "Women5",
        "gender": "women",
        "img": "./images/w5.jpeg",
        "price": 150,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ws5.jpeg",
        "discount": 35
    },
    {
        "idx": 11,
        "id": 110,
        "title": "Child1",
        "gender": "child",
        "img": "./images/c1.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/cs1.jpeg",
        "discount": 35
    },
    {
        "idx": 12,
        "id": 120,
        "title": "Child2",
        "gender": "child",
        "img": "./images/c2.jpeg",
        "price": 100,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/cs2.jpeg",
        "discount": 5
    },
    {
        "idx": 13,
        "id": 130,
        "title": "Child3",
        "gender": "child",
        "img": "./images/c3.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/cs3.jpeg",
        "discount": 65
    },
    {
        "idx": 14,
        "id": 140,
        "title": "Child4",
        "gender": "child",
        "img": "./images/c4.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/cs4.jpeg",
        "discount": 35
    },
    {
        "idx": 15,
        "id": 150,
        "title": "Child5",
        "gender": "child",
        "img": "./images/c5.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/cs5.jpeg",
        "discount": 9
    },
    {
        "idx": 16,
        "id": 160,
        "title": "Tv 1",
        "gender": "tv",
        "img": "./images/t1.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ts1.jpeg",
        "discount": 99
    },
    {
        "idx": 17,
        "id": 170,
        "title": "Tv 2",
        "gender": "tv",
        "img": "./images/t2.jpeg",
        "price": 1200,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ts2.jpeg",
        "discount": 59
    },
    {
        "idx": 18,
        "id": 180,
        "title": "Tv 3",
        "gender": "tv",
        "img": "./images/t3.jpeg",
        "price": 10000,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ts3.jpeg",
        "discount": 39
    },
    {
        "idx": 19,
        "id": 190,
        "title": "Tv 4",
        "gender": "tv",
        "img": "./images/t4.jpeg",
        "price": 1900,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ts4.jpeg",
        "discount": 99
    },
    {
        "idx": 20,
        "id": 200,
        "title": "Tv 5",
        "gender": "tv",
        "img": "./images/t5.jpeg",
        "price": 19000,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ts5.jpeg",
        "discount": 29
    },
    {
        "idx": 21,
        "id": 210,
        "title": "Mobile1",
        "gender": "mobile",
        "img": "./images/m1.jpeg",
        "price": 100,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms1.jpeg",
        "discount": 39
    },
    {
        "idx": 22,
        "id": 220,
        "title": "Mobile2",
        "gender": "mobile",
        "img": "./images/m2.jpeg",
        "price": 120,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms2.jpeg",
        "discount": 19
    },
    {
        "idx": 23,
        "id": 230,
        "title": "Mobile3",
        "gender": "mobile",
        "img": "./images/m3.jpeg",
        "price": 1080,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms3.jpeg",
        "discount": 38
    },
    {
        "idx": 24,
        "id": 240,
        "title": "Mobile4",
        "gender": "mobile",
        "img": "./images/m4.jpeg",
        "price": 3100,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms4.jpeg",
        "discount": 69
    },
    {
        "idx": 25,
        "id": 250,
        "title": "Mobile5",
        "gender": "mobile",
        "img": "./images/m5.jpeg",
        "price": 1050,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ms5.jpeg",
        "discount": 59
    },
    {
        "idx": 26,
        "id": 260,
        "title": "HeadPhone1",
        "gender": "head",
        "img": "./images/h1.jpeg",
        "price": 2800,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/hs1.jpeg",
        "discount": 89
    },
    {
        "idx": 27,
        "id": 270,
        "title": "HeadPhone2",
        "gender": "head",
        "img": "./images/h2.jpeg",
        "price": 3800,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/hs2.jpeg",
        "discount": 89
    },
    {
        "idx": 28,
        "id": 280,
        "title": "HeadPhone3",
        "gender": "head",
        "img": "./images/h3.jpeg",
        "price": 4800,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/hs3.jpeg",
        "discount": 8
    },
    {
        "idx": 29,
        "id": 290,
        "title": "HeadPhone4",
        "gender": "head",
        "img": "./images/h4.jpeg",
        "price": 5800,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/hs4.jpeg",
        "discount": 89
    },
    {
        "idx": 30,
        "id": 300,
        "title": "HeadPhone5",
        "gender": "head",
        "img": "./images/h5.jpeg",
        "price": 200,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/hs5.jpeg",
        "discount": 90
    },
    {
        "idx": 31,
        "id": 310,
        "title": "Laptop1",
        "gender": "laptop",
        "img": "./images/l1.jpeg",
        "price": 1990,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ls1.jpeg",
        "discount": 9
    },
    {
        "idx": 32,
        "id": 320,
        "title": "Laptop2",
        "gender": "laptop",
        "img": "./images/l2.jpeg",
        "price": 19990,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ls2.jpeg",
        "discount": 29
    },
    {
        "idx": 33,
        "id": 330,
        "title": "Laptop3",
        "gender": "laptop",
        "img": "./images/l3.jpeg",
        "price": 198990,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ls3.jpeg",
        "discount": 99
    },
    {
        "idx": 34,
        "id": 340,
        "title": "Laptop4",
        "gender": "laptop",
        "img": "./images/l4.jpeg",
        "price": 190990,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ls4.jpeg",
        "discount": 9
    },
    {
        "idx": 35,
        "id": 350,
        "title": "Laptop5",
        "gender": "laptop",
        "img": "./images/l5.jpeg",
        "price": 194590,
        "dec": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
        "like": 0,
        "sideimg": "./images/ls5.jpeg",
        "discount": 89
    }
]

console.log(carts);
// yfcyuciyciys